management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
    data:
      repository:
        autotime:
          enabled: true

server:
  tomcat:
    mbeanregistry:
      enabled: true